=== Ryan0mor/DAM_LM/3.2/reparaciones.dtd
<!ELEMENT reparaciones (reparacion)+>
<!ELEMENT reparacion (vehiculo, trabajoRelizado, factura)>
<!ELEMENT vehiculo (matricula, marca, modelo)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT trabajoRelizado (desc, duracion)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT factura (cod, totalAPagar, modoPago)>
<!ELEMENT cod (#PCDATA)>
<!ELEMENT totalAPagar (#PCDATA)>
<!ELEMENT modoPago (#PCDATA)>

=== Ryan0mor/DAM_LM/3.2/reparaciones.xml
<?xml version="1.0" encoding="UTF-8" standtalone="no"?>
<!DOCTYPE reparaciones SYSTEM "reparaciones.dtd">
<reparaciones>
    <reparacion>
        <vehiculo>
            <matricula></matricula>
            <marca></marca>
            <modelo></modelo>
        </vehiculo>
        <trabajoRelizado>
            <desc></desc>
            <duracion>40</duracion>
        </trabajoRelizado>
        <factura>
            <cod></cod>
            <totalAPagar></totalAPagar>
            <modoPago></modoPago>
        </factura>
    </reparacion>
    <reparacion>
        <vehiculo>
            <matricula></matricula>
            <marca></marca>
            <modelo></modelo>
        </vehiculo>
        <trabajoRelizado>
            <desc></desc>
            <duracion></duracion>
        </trabajoRelizado>
        <factura>
            <cod></cod>
            <totalAPagar></totalAPagar>
            <modoPago></modoPago>
        </factura>
    </reparacion>
</reparaciones>
